# Generated by Django 4.2.19 on 2025-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المشروع")),
                ("description", models.TextField(verbose_name="وصف المشروع")),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("end_date", models.DateField(verbose_name="تاريخ الانتهاء المتوقع")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "مكتمل"),
                            ("on_hold", "معلق"),
                            ("cancelled", "ملغي"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الميزانية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "المشروع",
                "verbose_name_plural": "المشاريع",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المهمة"),
                ),
                ("description", models.TextField(verbose_name="وصف المهمة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "للتنفيذ"),
                            ("in_progress", "قيد التنفيذ"),
                            ("review", "قيد المراجعة"),
                            ("completed", "مكتمل"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("medium", "متوسطة"),
                            ("high", "عالية"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="الأولوية",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                ("due_date", models.DateField(verbose_name="تاريخ الاستحقاق")),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="الساعات المقدرة",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="الساعات الفعلية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإكمال"
                    ),
                ),
            ],
            options={
                "verbose_name": "المهمة",
                "verbose_name_plural": "المهام",
                "ordering": ["-created_at"],
            },
        ),
    ]
