# Generated by Django 4.2.19 on 2025-02-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/images/",
                verbose_name="صور المشروع",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_plans",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projects/plans/",
                verbose_name="مخططات المشروع",
            ),
        ),
    ]
