# Generated by Django 4.2.19 on 2025-02-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.product",
                verbose_name="المنتج",
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchases.purchase",
                verbose_name="عملية الشراء",
            ),
        ),
    ]
