# Generated by Django 4.2.19 on 2025-02-18 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdashboardpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_preference",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="userdashboardpreference",
            name="widgets",
            field=models.ManyToManyField(
                through="dashboard.UserWidgetSettings",
                to="dashboard.dashboardwidget",
                verbose_name="العناصر",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userwidgetsettings",
            unique_together={("user_preference", "widget")},
        ),
    ]
