# Generated by Django 4.2.19 on 2025-02-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("call", "اتصال"),
                            ("meeting", "اجتماع"),
                            ("email", "بريد إلكتروني"),
                            ("note", "ملاحظة"),
                            ("task", "مهمة"),
                        ],
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="الموضوع")),
                ("description", models.TextField(verbose_name="الوصف")),
                ("date", models.DateTimeField(verbose_name="التاريخ")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "النشاط",
                "verbose_name_plural": "الأنشطة",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="الشركة"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "الموقع الإلكتروني"),
                            ("referral", "إحالة"),
                            ("social_media", "وسائل التواصل الاجتماعي"),
                            ("direct", "مباشر"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="المصدر",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("contacted", "تم التواصل"),
                            ("qualified", "مؤهل"),
                            ("proposal", "تم تقديم عرض"),
                            ("negotiation", "قيد التفاوض"),
                            ("won", "تم الكسب"),
                            ("lost", "خسارة"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "العميل المحتمل",
                "verbose_name_plural": "العملاء المحتملون",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="القيمة المتوقعة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "تم التحديد"),
                            ("qualified", "مؤهل"),
                            ("proposal", "تم تقديم عرض"),
                            ("negotiation", "قيد التفاوض"),
                            ("closed_won", "مغلق - ناجح"),
                            ("closed_lost", "مغلق - خاسر"),
                        ],
                        default="identified",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(verbose_name="تاريخ الإغلاق المتوقع"),
                ),
                (
                    "probability",
                    models.IntegerField(default=50, verbose_name="احتمالية النجاح (%)"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "الفرصة",
                "verbose_name_plural": "الفرص",
                "ordering": ["-created_at"],
            },
        ),
    ]
